# Generated by Django 4.2.7 on 2023-12-14 12:10

import app1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='reference_id',
            field=models.CharField(default=app1.models.generate_uuid, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
